config/routes.rb
Dassist::Application.routes.draw do
  devise_for :users

  match 'projects/sort' => 'projects#prioritize_tasks', :method => :post
  resources :users do
    resources :projects
  end
  
  resources :projects do 
    resources :messages
  end
  

  root :to => "welcome#index"

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  acts_as_list default_scope => 'position'
  belongs_to :user
  has_many :messages
  def self.upgrade_position( position_array )
    for id in position_array
      project = Project.find_by_id( id.to_i ) 
      project.position = position_array.index( project.id.to_s ) + 1
      project.save
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :messages
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  
  
  layout :layout_by_resource

  def layout_by_resource
    if devise_controller? && resource_name == :user && action_name == 'new'
      "authentication/signup"
    else
      "application"
    end
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end
  
  def create 
    @project = Project.find_by_id( params[:project_id])
    @message = @project.messages.new( params[:message] )
    @message.user = current_user
    @message.save
    
    
    respond_to do |format|
      format.html { render :action => "edit" }
      format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      format.js {   }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end
  
  def prioritize_tasks
    # user_story = UserStory.find(params[:id])
    # tasks = user_story.tasks
    # tasks.each do |task|
    #   task.position = params['task'].index(task.id.to_s) + 1
    #   task.save
    # end
    # projects = Project.find(:all , :conditions => {:active => true })
    # projects.each do |project|
    #   #
    #   project.position = params['project'].index(project.id.to_s) + 1
    #   project.save
    # end
        # 
    Project.upgrade_position( params['project'] )
    render :nothing => true
  end
  
  

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index 
    @projects = Project.find( :all , :order => 'position ASC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def master_class( params )
    "current" if params[:controller].match /^master/
  end
  
  def dashboard_nav( params ) 
    # "layouts/dashboard/master_dashboard_nav" if params[:controller].match /^master/
    "layouts/dashboard/master_dashboard_nav"
  end
  
  def button_for(name, options={})
    return content_tag(:button, content_tag(:span, content_tag(:span, name)), :class => options[:class], :type => options[:button_type])
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_admin_css.html.erb
<!--CSS-->
<link rel="stylesheet" href="/stylesheets/yourAdmin/reset.css" type="text/css" />
<link rel="stylesheet" href="/stylesheets/yourAdmin/styles.css" type="text/css" />
<!--<link rel="stylesheet" href="css/altlayout.css" type="text/css" />-->
<!-- Google Fonts -->
<link href='http://fonts.googleapis.com/css?family=Droid+Serif:regular,italic' rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Droid+Sans:regular,bold' rel='stylesheet' type='text/css' />

app/views/layouts/_admin_javascripts.html.erb
<!--Scripts-->
<!--jQuery-->
<%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
<script src="/javascripts/jquery/jquery.js" type="text/javascript"></script>
<!--jQuery Superfish-->
<script src="/javascripts/jquery-superfish/superfish.js" type="text/javascript"></script>
<!--jQuery Visualize-->
<script src="/javascripts/jquery-visualize/visualize.jQuery.js" type="text/javascript"></script>
<link href="/javascripts/jquery-visualize/visualize.css" rel="stylesheet" type="text/css">
<!--jQuery Uniform-->
<script src="/javascripts/jquery-uniform/jquery.uniform.min.js" type="text/javascript"></script>
<link href="/javascripts/jquery-uniform/css/uniform.default.css" rel="stylesheet" type="text/css">
<!--jQuery Tipsy-->
<script src="/javascripts/jquery-tipsy/jquery.tipsy.js" type="text/javascript"></script>
<link href='/javascripts/jquery-tipsy/tipsy.css' rel='stylesheet' type='text/css' />
<!--jQuery Datatables-->
<script src="/javascripts/jquery-datatables/jquery.dataTables.min.js" type="text/javascript"></script>
<!--jQuery Facebox-->
<script src="/javascripts/jquery-facebox/facebox.js" type="text/javascript"></script>
<link rel="stylesheet" href="/javascripts/jquery-facebox/facebox.css" type="text/css" />



<!-- jQuery UI -->
<!-- <script src="/javascripts/autoresize.jquery.min.js" type="text/javascript"></script> -->
<script src="/javascripts/auto-grow.js" type="text/javascript"></script>
<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js" %>
<!-- autoResize text area -->

<!--Script Loader-->
<script src="/javascripts/loader.js" type="text/javascript"></script>

app/views/layouts/_box_content.html.erb
<!--Content-->
<div class="content padding">
  <ul class="inbox">
    <% for message in project.messages %>
      <%= render :partial => "messages/message" , :locals => { :message => message }%>
    <% end %>
    
    <%= render :partial => "messages/message_form", :locals => { :project => project } %>
    <!--separator-->
    
    
    <!--separator-->
    <!-- <li class="separator"></li> -->
  </ul>
</div>

app/views/layouts/_box_content2.html.erb
<!--Content-->
<div class="content padding">
  <ul class="inbox">
    <li> 
      <!--Avatar--> 
      <img alt="avatar" class="avatar" src="/images/assets/user.png" width="35" height="35"/> 
      <!--Author-->
      <div class="author"> <a href="#"></a>
        <h4><a href="#">Willy Y. Wirawan</a></h4>
      </div>
      <!--Meta-->
      <div class="meta"> <a href="#">January 22, 2011 at 4:43 pm</a> </div>
      <!--Body-->
      <div class="body">
        <p>
          Boss, menara Telkomsel di Ekor butuh dipercepat nih. Soalnya control keadaan lapangan
          sangat sulit kalau musti melalui telephone satelit (secara kita cuman punya 2 biji).
        </p>
      </div>
    </li>
    <!--separator-->
    <li class="separator"></li>
    <li> 
      <!--Avatar--> 
      <img alt="avatar" class="avatar" src="/images/assets/user.png" width="35" height="35"/> 
      <!--Author-->
      <div class="author"> <a href="#"></a>
        <h4><a href="#">Sudirman Utomo</a></h4>
      </div>
      <!--Meta-->
      <div class="meta"> <a href="#">January 22, 2011 at 4:43 pm</a>  </div>
      <!--Body-->
      <div class="body">
        <p>
          Emang kenapa yah Wil? Bukannya kata Pak Norman sudah bisa buat sms atau nelpon 2-3 orang? 
          Lagipula, saya sudah tanya Pak LHS. Kata dia masih ok tuh. 
        </p>
      </div>
    </li>
    <!--separator-->
    <li class="separator"></li>
    <li> 
      <!--Avatar--> 
      <img alt="avatar" class="avatar" src="/images/assets/user.png" width="35" height="35"/> 
      <!--Author-->
      <div class="author"> <a href="#"></a>
        <h4><a href="#">Denny Wahyono</a></h4>
      </div>
      <!--Meta-->
      <div class="meta"> <a href="#">January 22, 2011 at 4:43 pm</a></div>
      <!--Body-->
      <div class="body">
        <p>
          Buat komunikasi sih emang masih OKE. Cumannya, itu repeater, kita sudah deal ama BGS 
          buat gratis pasang di Obi (TBP, soalnya sinyal disono kehalang bukit) + yang di Ekor 
          di tuker sama yang baru. Lumayan kan hemat 150 juta.
        </p>
      </div>
    </li>
  </ul>
</div>

app/views/layouts/_content.html.erb
<!--Content-->
<div id="content">
  <div class="container clearfix" id="projects"> 
    
    <% for project in @projects %>
      <div class="box hidden" id="project_<%= project.id %>"> 
        <!--Title-->
        <div class="header">
          <h2><a href="#"><%= project.name %></a></h2>
          <!--Draggable--> 
          <span class="draggable"></span> <span class="toggle"></span> 
        </div>
        <%= render :partial => "layouts/box_content" , :locals => {:project => project} %>
      </div>
    <% end %>





    <!--Footer-->
    <div id="footer" class="separator"> 
      <!-- Remove this notice or replace it with whatever you want --> 
      &#169; Copyright 2011 Harita |  <a href="#">Top</a> </div>
      <!--End .container--> 
    </div>
    <!--End #content--> 
  </div>


<!--content for adding new category -->
<div id="modal_new_master_category" style="display:none;">
  <%# form_for @category, :html=> {:class => "modal_form"} do |f| %>
  <%#= f.label :name  , "New Category Name" %>
  <%#= f.text_field :name %>
  <%#= f.submit "Submit", :class => "button modal_submit"%>
  <%# end %>
  <div>
  <!--demo content for facebox-->
  <div id="modaldemo" style="display:none;">
    <ul class="inbox">
      <li> 
        <!--Avatar--> 
        <img alt="avatar" class="avatar" src="/images/assets/user.png" width="35" height="35"/> 
        <!--Author-->
        <div class="author"> <a href="#"></a>
          <h4><a href="#">Username</a></h4>
        </div>
        <!--Meta-->
        <div class="meta"> <a href="#">January 22, 2011 at 4:43 pm</a> - <a href="#">Reply</a> </div>
        <!--Body-->
        <div class="body">
          <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non nulla sapien, quis luctus felis. Fusce sodales tempus tincidunt. </p>
        </div>
      </li>
      <!--separator-->
      <li class="separator"></li>
      <li> 
        <!--Avatar--> 
        <img alt="avatar" class="avatar" src="/images/assets/user.png" width="35" height="35"/> 
        <!--Author-->
        <div class="author"> <a href="#"></a>
          <h4><a href="#">Username</a></h4>
        </div>
        <!--Meta-->
        <div class="meta"> <a href="#">January 22, 2011 at 4:43 pm</a> - <a href="#">Reply</a> </div>
        <!--Body-->
        <div class="body">
          <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non nulla sapien, quis luctus felis. Fusce sodales tempus tincidunt. </p>
        </div>
      </li>
      <!--separator-->
      <li class="separator"></li>
      <li> 
        <!--Avatar--> 
        <img alt="avatar" class="avatar" src="/images/assets/user.png" width="35" height="35"/> 
        <!--Author-->
        <div class="author"> <a href="#"></a>
          <h4><a href="#">Username</a></h4>
        </div>
        <!--Meta-->
        <div class="meta"> <a href="#">January 22, 2011 at 4:43 pm</a> - <a href="#">Reply</a> </div>
        <!--Body-->
        <div class="body">
          <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non nulla sapien, quis luctus felis. Fusce sodales tempus tincidunt. </p>
        </div>
      </li>
    </ul>
  </div>

<%#= link_to "", edit_master_category_url(":id") , :style=>"display:none;" , :id=> "edit_category_link"%>
<%#= link_to "", master_category_url(":id") , :style=>"display:none;" , :id=> "destroy_category_link"%>
<img src="/images/ajax-loader.gif" style="display:none;" id="ajax-loader" class="ajax-loader" />
</body>

app/views/layouts/_header.html.erb
<!--Header-->
<div id="header"> 
  <!--Container-->
  <div class="container clearfix"> 
    
    <%= render :partial => "layouts/logo_menu" %>
    
    <%= render :partial => dashboard_nav( params )  %>
    
    <!--end container--> 
  </div>
  <!--end #header--> 
</div>

app/views/layouts/_logo_menu.html.erb
<!--Logo--> 
<img id="logo" src="/images/assets/logo.png" alt="logo" /> 
<!--Menu-->
<ul id="menu" class="clearfix">
  <li><a class="" href="index.html">Dashboard</a></li>
  <!-- <li><a href="typography.html">MasterData</a></li> -->
  <li><a href="#">MasterData</a></li>
  <li class="dropdown"> <a href="settings.html">Settings</a>
    <ul>
      <li>Section</li>
      <li><a href="#">Section #1</a></li>
      <li><a href="#">Section #2</a></li>
    </ul>
  </li>
  <li><a href="login.html">Logout</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title>yourAdmin</title>
  
  <%= render :partial => "layouts/admin_css" %>
  <%= render :partial => "layouts/admin_javascripts" %>


  <%= csrf_meta_tag %>

</head>
<body>
<%= render :partial => "layouts/header" %>

<%= render :partial =>"layouts/content" %>

</body>
</html>

app/views/layouts/authentication/signup.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title>yourAdmin | Login</title>
  
  <%= render :partial => "layouts/admin_css" %>
  <%= render :partial => "layouts/admin_javascripts" %>
  <%= csrf_meta_tag %>
</head>

<body>

<!--Content-->
<div id="content">
  <div id="login" class="container"> 
    <img class="logo" src="/images/assets/logo.png" alt="logo" />
    <!--Login-->
    <div class="box">
      <div class="header">
        <h2>Login</h2>
      </div>
      <div class="content login-content">
        <div class="tabs"> 
          <!--navigation-->
          <ul class="navigation clearfix">
            <li> <a class="current" href="#tab1">Login</a></li>
            <li><a href="#tab2">Register</a></li>
            <li><a href="#tab3">Recover Password</a></li>
          </ul>
          <!--tab1-->
          <div class="tab" id="tab1">
            <!-- <p class="message valid">
              Sucess Message
              <span class="close">X</span>
            </p>
            <p class="message invalid">
              Error Message
              <span class="close">X</span>
            </p> -->
            
            <%= form_for(resource, :as => resource_name, :url => session_path(resource_name),
                         :html => {:class=>"form"}) do |f| %>
              <p>
                <%= f.label :email , :class => "field" %>
                <%= f.email_field :email %>
              </p>

              <p>
                <%= f.label :password, :class => "field" %>
                <%= f.password_field :password %>
              </p>

              <p class="field">
                <%= button_for("Submit", :button_type => "submit") %>
                <%= button_for("Submit", :button_type => "submit", :class => "secondary") %>
              </p>
            <% end %>
            
            <!--             
                        <form action="index.html" method="post" class="form">
                          <p class="field">
                            <label>Email </label>
                            <input class="large" id="email-willy">
                          </p>
                          <p class="field">
                            <label for="username">Password </label>
                            <input id="username-willy" name="username" class="large">
                          </p>
                          <p class="field">
                            <button type="submit">Submit</button>
                            <button type="reset" class="secondary">Reset</button>
                          </p>
                        </form> -->
          </div>
          <!--tab2-->
          <div class="tab" id="tab2">
            <form action="#" method="post" class="form">
              <p class="field">
                <label for="username">Email </label>
                <input id="username" name="username" class="large">
              </p>
              <!--               <p class="field">
                              <label for="username">Password </label>
                              <input name="email" type="password" class="large" id="email">
                            </p> -->
              <p class="field">
                <button type="submit">Register</button>
                <button type="reset" class="secondary">Reset</button>
              </p>
            </form>
          </div>
          <!--tab3-->
          <div class="tab" id="tab3">
            <form action="#" method="post" class="form">
              <p>Your password will be sent to your email account.</p>
              <p class="field">
                <label for="username">Email </label>
                <input id="username" name="username" class="large">
              </p>
              <p class="field">
                <button type="submit">Submit</button>
                <button type="reset" class="secondary">Reset</button>
              </p>
            </form>
          </div>

          <!--End .tabs-->
        </div>    	
        <!--End .content-->	
      </div>
      <!--End .box-->
    </div>
    <!--End .container-->
  </div>
  <!--End #content-->
</div>
</body>
</html>

app/views/layouts/dashboard/_master_dashboard_nav.html.erb
<!--DashboardNavigation-->
<ul class="clearfix" id="navigation">
  <li class="current"><a class="current" href="#"><img alt="dashboard" class="icon" src="/images/assets/dashboard.png"/>InProgress</a></li>
  <li><a href="#modaldemo" rel="modal"><img alt="inbox" class="icon" src="/images/assets/inbox.png"/>Notification<span class="notification" rel="tooltip" original-title="You have 15 new messages">15</span></a>
    <ul>
      <li><a href="#" title="">Write New</a></li>
      <li><a href="#" title="">Junk</a></li>
      <li><a href="#" title="">Deleted</a></li>
    </ul>
  </li>
  <li> <a href="#"><img alt="layout" class="icon" src="/images/assets/layout.png"/>Finished</a>
    <ul>
      <li><a href="#" title="">Add New</a></li>
      <li><a href="#" title="">Edit</a></li>
      <li><a href="#" title="">View</a></li>
    </ul>
  </li>
  <li><a href="http://themeforest.com" title="Navigation with Link" target="_new"><img alt="statistics" class="icon" src="/images/assets/statistics.png"/>Statistics</a></li>
  <li class="separator"></li>
</ul>

app/views/messages/_message.html.erb
<li> 
  <!--Avatar--> 
  <img alt="avatar" class="avatar" src="/images/assets/user.png" width="35" height="35"/> 
  <!--Author-->
  <div class="author"> <a href="#"></a>
    <h4><a href="#"><%= message.user.name %></a></h4>
  </div>
  <!--Meta-->
  <div class="meta"> <a href="#">January 22, 2011 at 4:43 pm</a> </div>
  <!--Body-->
  <div class="body">
    <p>
      <%= message.content %>
    </p>
  </div>
</li>
<li class="separator"></li>

app/views/messages/_message_form.html.erb
<li class="message-form"> 
  <!--Avatar--> 
  <img alt="avatar" class="avatar" src="/images/assets/user.png" width="35" height="35"/> 
  <!--Author-->
  <div class="author"> <a href="#"></a>
    <h4><a href="#"><%= current_user.name %></a></h4>
  </div>
  <!--Meta-->
  <div class="meta"> </div>
  <!--Body-->
  <div class="body">
    <% form_for project.messages.new, :url => project_messages_url( project.id ), 
    :html => {:class=> "form_message" , :id => "form_project_message_#{project.id}"} do |f| %>
      <%= f.text_area :content , :cols => 100, :rows => 1 ,:class => "autoResize" %><br />
      <%= f.submit %>
    <% end %>
  </div>
</li>

app/views/messages/_project_message_update.html.erb
<%= render :partial => "message" , :locals => { :message => @message } %>
<%= render :partial => "message_form", :locals => { :project => @message.project }  %>

app/views/messages/create.js.erb
jQuery(document).ready(function($) {
	$("div#project_<%= @message.project.id %> li.message-form").replaceWith(
	  '<%= escape_javascript( render  :partial => "project_message_update" )%>');
	  
	//rebinding? 
	
});

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Position</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.position %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Position:</b>
  <%= @project.position %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>